export const UNABLE_TO_CREATE_USER = 'Unable to create user'
export const INVALID_EMAIL = 'Unable to create user due to invalid email'
export const INVALID_PASSWORD = 'Unable to create user due to invalid password'
export const UNABLE_TO_GENERATE_TOKEN = 'Unable to generate JWT for user'
export const MISSING_FIELDS = 'Unable to create user due to missing fields'
export const UNABLE_TO_FIND_USER = 'Unable to find user'
