name: Deploy

on:
  push:
    branches:
      - develop
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - uses: ./../.github/workflows/ci.yml

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/267063385539/locations/global/workloadIdentityPools/dev-ultmt-pool/providers/dev-ultmt-provider'
          service_account: 'ultmt-service-account@dev-ultmt-app.iam.gserviceaccount.com'
      
      - name: "Deploy Registry"
        run: |
          gcloud builds submit --tag 'gcr.io/dev-ultmt-app/ultmt-api' .

      - name: "Deploy cloud Run"
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'ultmt-api'
          image: 'gcr.io/dev-ultmt-app/ultmt-api'

